# Generated by Django 3.0.6 on 2022-12-14 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='cvs/', verbose_name='Βιογραφικό')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ημερ. Δημιουργίας')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('del_f', models.BooleanField(default=False, verbose_name='Διαγραμμένο')),
            ],
            options={
                'verbose_name': 'Βιογραφικό',
                'verbose_name_plural': 'Βιογραφικά',
                'ordering': ['-created'],
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Τίτλος Πτυχείου(*)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερ. Δημιουργίας')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('del_f', models.BooleanField(default=False, verbose_name='Διαγραμμένο')),
            ],
            options={
                'verbose_name': 'Πτυχείο',
                'verbose_name_plural': 'Πτυχεία',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=200, verbose_name='Επώνυμο')),
                ('FirstName', models.CharField(max_length=200, verbose_name='Όνομα')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='E-mail')),
                ('Mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Κινητό')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Ημερ. Δημιουργίας')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvapp2022byte.Degree', verbose_name='Πτυχείο')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvdoc', to='cvapp2022byte.CVDoc', verbose_name='Βιογραφικό')),
            ],
            options={
                'verbose_name': 'Βιογραφικό',
                'verbose_name_plural': 'Βιογραφικά',
            },
        ),
    ]
