# Generated by Django 3.0.6 on 2022-12-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp2022byte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='file',
            field=models.FileField(max_length=255, upload_to='cvs/', verbose_name='Βιογραφικό'),
        ),
        migrations.DeleteModel(
            name='CVDoc',
        ),
    ]
